<?php
$_mailData['info']['fromName'] = "SUV専門店　OS INC";
$_mailData['info']['fromEmail'] = "suv@os-inc.jp";
$_mailData['info']['toEmail'] = "suv@os-inc.jp.jp,all.osinc.staff@gmail.com,osinc.staff.suv@gmail.com,hp@1zsbz8qe312lgowwjlo8o6dyb6qbcucqkkvdf5scrcpostyrgh.2t-exqieay.ap12.apex.salesforce.com,r-aoyama@ctn-net.co.jp";
$_mailData['info']['subject'] = "【SUV専門店・株式会社OS】お問合せありがとうございます。";
$_mailData['info']['subjectC'] = "ホームページよりお問合せがありました。";
$_mailData['info']['msg'] = "%name%様

お問合わせいただいた内容は下記の通りです。
後日ご返答させていただきます。

%msgData%


株式会社OS SUV専門店
〒587-0002 大阪府堺市美原区黒山652-1
TEL：072-289-8070
営業時間：10:00～19:00
定休日：水曜日/木曜日";
$_mailData['zaiko']['fromName'] = "SUV専門店　OS INC";
$_mailData['zaiko']['fromEmail'] = "suv@os-inc.jp";
$_mailData['zaiko']['toEmail'] = "suv@os-inc.jp.jp,all.osinc.staff@gmail.com,osinc.staff.suv@gmail.com,hp@1zsbz8qe312lgowwjlo8o6dyb6qbcucqkkvdf5scrcpostyrgh.2t-exqieay.ap12.apex.salesforce.com,r-aoyama@ctn-net.co.jp";
$_mailData['zaiko']['subject'] = "【SUV専門店・株式会社OS】在庫車お問合わせありがとうございます";
$_mailData['zaiko']['subjectC'] = "ホームページより在庫車お問合わせがありました。";
$_mailData['zaiko']['msg'] = "%name%様

お問合わせいただいた内容は下記の通りです。
後日ご返答させていただきます。

%msgData%


株式会社OS SUV専門店
〒587-0002 大阪府堺市美原区黒山652-1
TEL：072-289-8070
営業時間：10:00～19:00
定休日：水曜日/木曜日";
$_mailData['purchase']['fromName'] = "SUV専門店　OS INC";
$_mailData['purchase']['fromEmail'] = "suv@os-inc.jp";
$_mailData['purchase']['toEmail'] = "suv@os-inc.jp.jp,all.osinc.staff@gmail.com,osinc.staff.suv@gmail.com,r-aoyama@ctn-net.co.jp";
$_mailData['purchase']['subject'] = "【SUV専門店・株式会社OS】買取査定のお申込みありがとうございます";
$_mailData['purchase']['subjectC'] = "買取査定のお申込みがありました";
$_mailData['purchase']['msg'] = "%name%様

買取査定のお申込みありがとうございます。
内容は下記の通りとなります。
後日ご返答させていただきます。

%msgData%

株式会社OS SUV専門店
〒587-0002 大阪府堺市美原区黒山652-1
TEL：072-289-8070
営業時間：10:00～19:00
定休日：水曜日/木曜日";
$_mailData['reserve']['fromName'] = "SUV専門店　OS INC";
$_mailData['reserve']['fromEmail'] = "suv@os-inc.jp";
$_mailData['reserve']['toEmail'] = "suv@os-inc.jp.jp,all.osinc.staff@gmail.com,osinc.staff.suv@gmail.co,hp@1zsbz8qe312lgowwjlo8o6dyb6qbcucqkkvdf5scrcpostyrgh.2t-exqieay.ap12.apex.salesforce.com,r-aoyama@ctn-net.co.jp";
$_mailData['reserve']['subject'] = "【SUV専門店・株式会社OS】ご来店予約ありがとうございます";
$_mailData['reserve']['subjectC'] = "ホームページよりご来店予約がありました";
$_mailData['reserve']['msg'] = "%name%様

ご来店予約いただいた内容は下記の通りです。
確認次第、ご返答させていただきます。

%msgData%


株式会社OS SUV専門店
〒587-0002 大阪府堺市美原区黒山652-1
TEL：072-289-8070
営業時間：10:00～19:00
定休日：水曜日/木曜日";
?>